//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Mouse"",
            ""id"": ""6d638e77-13f6-4a57-b0d9-a619d6d5cf68"",
            ""actions"": [
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""6b7385b3-bf8f-419d-b0ad-e4e7a13c333e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""dc1f542f-eb49-4741-a972-2afddd630d15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Middle"",
                    ""type"": ""Button"",
                    ""id"": ""4c79e2a4-5d6d-4c41-92a5-9d4616645b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""269d56da-c50b-48ee-b454-b74d545bc570"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e0511e1-44ba-4356-b0ef-46f2b0976b98"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dea38719-afa5-44e2-a73f-9b0b8e82fd95"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Middle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraInGame"",
            ""id"": ""ed074946-88ec-43b9-93c5-b765cc65538f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5bb5c8a0-8afb-428f-ad4b-8e631563f53e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""642110ed-6f86-4d92-a2db-224c47dde65e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""a13ae175-cb51-4ef7-9c2f-bf0a51b330b5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6aafdd00-39b3-48c1-af4f-66be45139471"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1ade69a-ca48-4c13-8570-0da0ec34af50"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""10a4007d-b5be-4a30-aa2c-b0b3de92cc5e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0dcb1654-6cb0-412e-b281-20537331627b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""8a174238-f158-4cbf-a0ca-da850c0bae15"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""946252cb-8767-45bd-beb8-4d0d670430c2"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""783f0135-6eef-4c44-9a64-45b7ffd72c98"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""BuildKeys"",
            ""id"": ""29f5212c-db49-4355-82f9-fb66633d9914"",
            ""actions"": [
                {
                    ""name"": ""MultiBuild"",
                    ""type"": ""Button"",
                    ""id"": ""6c21c3e9-2802-43bd-9ef3-d29af618ff17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""9481fac0-f3d4-4d89-9b5e-348b4716bc6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""133f8869-717d-49a7-b356-56929c265ee9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""6d479b1a-908b-48b1-885f-e8376fceac88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""ac2f48d0-2653-4ace-8d0d-7496359bf1d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""3698031e-6507-4426-9ffe-457d8a152f21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""7d95b92c-a534-49f8-92d8-ab1b3722e25d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""d8ed9c72-6d7a-46cc-b6cd-6eb35df20dee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""bff0a52e-a45e-4fc9-8629-239c5f22cfa1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""77c3f1b8-78ab-41a4-9bd5-749163b4f4c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""6fdd3422-6d52-45e2-8663-5b4366216bab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Upgrade"",
                    ""type"": ""Button"",
                    ""id"": ""1b550666-ec4e-408e-9099-2d367b50e474"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5bd3f877-c03e-4b88-a87b-fe040ce6c90f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MultiBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51d1d456-bda9-4b10-8949-f2c5b19eab0b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c9ddc20-fd53-4895-865b-98b195f88725"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e541f894-3005-4964-bf42-a5ed5a930e34"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd72bd21-3c25-4b8a-bb73-14a7e24bbe09"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5013980-9f04-4368-87cb-36fbd6907afc"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""291a2d1e-c9d9-4e28-8703-e3cff78586ee"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""815e35b4-a397-4c3b-a33c-d66b931b0d36"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Upgrade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0beac8ad-1e09-4281-81a3-c27a310e53ca"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""293d9424-ac89-4a33-a486-078208c84856"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""006616fd-3eb1-4546-b06f-6a6db0092e54"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ebf2f6-385d-498c-9c7a-517896853f77"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": []
        }
    ]
}");
        // Mouse
        m_Mouse = asset.FindActionMap("Mouse", throwIfNotFound: true);
        m_Mouse_Left = m_Mouse.FindAction("Left", throwIfNotFound: true);
        m_Mouse_Right = m_Mouse.FindAction("Right", throwIfNotFound: true);
        m_Mouse_Middle = m_Mouse.FindAction("Middle", throwIfNotFound: true);
        // CameraInGame
        m_CameraInGame = asset.FindActionMap("CameraInGame", throwIfNotFound: true);
        m_CameraInGame_Move = m_CameraInGame.FindAction("Move", throwIfNotFound: true);
        m_CameraInGame_Zoom = m_CameraInGame.FindAction("Zoom", throwIfNotFound: true);
        // BuildKeys
        m_BuildKeys = asset.FindActionMap("BuildKeys", throwIfNotFound: true);
        m_BuildKeys_MultiBuild = m_BuildKeys.FindAction("MultiBuild", throwIfNotFound: true);
        m_BuildKeys_One = m_BuildKeys.FindAction("One", throwIfNotFound: true);
        m_BuildKeys_Two = m_BuildKeys.FindAction("Two", throwIfNotFound: true);
        m_BuildKeys_Three = m_BuildKeys.FindAction("Three", throwIfNotFound: true);
        m_BuildKeys_Four = m_BuildKeys.FindAction("Four", throwIfNotFound: true);
        m_BuildKeys_Five = m_BuildKeys.FindAction("Five", throwIfNotFound: true);
        m_BuildKeys_Six = m_BuildKeys.FindAction("Six", throwIfNotFound: true);
        m_BuildKeys_Seven = m_BuildKeys.FindAction("Seven", throwIfNotFound: true);
        m_BuildKeys_Eight = m_BuildKeys.FindAction("Eight", throwIfNotFound: true);
        m_BuildKeys_Nine = m_BuildKeys.FindAction("Nine", throwIfNotFound: true);
        m_BuildKeys_Zero = m_BuildKeys.FindAction("Zero", throwIfNotFound: true);
        m_BuildKeys_Upgrade = m_BuildKeys.FindAction("Upgrade", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mouse
    private readonly InputActionMap m_Mouse;
    private List<IMouseActions> m_MouseActionsCallbackInterfaces = new List<IMouseActions>();
    private readonly InputAction m_Mouse_Left;
    private readonly InputAction m_Mouse_Right;
    private readonly InputAction m_Mouse_Middle;
    public struct MouseActions
    {
        private @PlayerControls m_Wrapper;
        public MouseActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Left => m_Wrapper.m_Mouse_Left;
        public InputAction @Right => m_Wrapper.m_Mouse_Right;
        public InputAction @Middle => m_Wrapper.m_Mouse_Middle;
        public InputActionMap Get() { return m_Wrapper.m_Mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void AddCallbacks(IMouseActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseActionsCallbackInterfaces.Add(instance);
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Middle.started += instance.OnMiddle;
            @Middle.performed += instance.OnMiddle;
            @Middle.canceled += instance.OnMiddle;
        }

        private void UnregisterCallbacks(IMouseActions instance)
        {
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Middle.started -= instance.OnMiddle;
            @Middle.performed -= instance.OnMiddle;
            @Middle.canceled -= instance.OnMiddle;
        }

        public void RemoveCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseActions @Mouse => new MouseActions(this);

    // CameraInGame
    private readonly InputActionMap m_CameraInGame;
    private List<ICameraInGameActions> m_CameraInGameActionsCallbackInterfaces = new List<ICameraInGameActions>();
    private readonly InputAction m_CameraInGame_Move;
    private readonly InputAction m_CameraInGame_Zoom;
    public struct CameraInGameActions
    {
        private @PlayerControls m_Wrapper;
        public CameraInGameActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CameraInGame_Move;
        public InputAction @Zoom => m_Wrapper.m_CameraInGame_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_CameraInGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraInGameActions set) { return set.Get(); }
        public void AddCallbacks(ICameraInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraInGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraInGameActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        private void UnregisterCallbacks(ICameraInGameActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        public void RemoveCallbacks(ICameraInGameActions instance)
        {
            if (m_Wrapper.m_CameraInGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraInGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraInGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraInGameActions @CameraInGame => new CameraInGameActions(this);

    // BuildKeys
    private readonly InputActionMap m_BuildKeys;
    private List<IBuildKeysActions> m_BuildKeysActionsCallbackInterfaces = new List<IBuildKeysActions>();
    private readonly InputAction m_BuildKeys_MultiBuild;
    private readonly InputAction m_BuildKeys_One;
    private readonly InputAction m_BuildKeys_Two;
    private readonly InputAction m_BuildKeys_Three;
    private readonly InputAction m_BuildKeys_Four;
    private readonly InputAction m_BuildKeys_Five;
    private readonly InputAction m_BuildKeys_Six;
    private readonly InputAction m_BuildKeys_Seven;
    private readonly InputAction m_BuildKeys_Eight;
    private readonly InputAction m_BuildKeys_Nine;
    private readonly InputAction m_BuildKeys_Zero;
    private readonly InputAction m_BuildKeys_Upgrade;
    public struct BuildKeysActions
    {
        private @PlayerControls m_Wrapper;
        public BuildKeysActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MultiBuild => m_Wrapper.m_BuildKeys_MultiBuild;
        public InputAction @One => m_Wrapper.m_BuildKeys_One;
        public InputAction @Two => m_Wrapper.m_BuildKeys_Two;
        public InputAction @Three => m_Wrapper.m_BuildKeys_Three;
        public InputAction @Four => m_Wrapper.m_BuildKeys_Four;
        public InputAction @Five => m_Wrapper.m_BuildKeys_Five;
        public InputAction @Six => m_Wrapper.m_BuildKeys_Six;
        public InputAction @Seven => m_Wrapper.m_BuildKeys_Seven;
        public InputAction @Eight => m_Wrapper.m_BuildKeys_Eight;
        public InputAction @Nine => m_Wrapper.m_BuildKeys_Nine;
        public InputAction @Zero => m_Wrapper.m_BuildKeys_Zero;
        public InputAction @Upgrade => m_Wrapper.m_BuildKeys_Upgrade;
        public InputActionMap Get() { return m_Wrapper.m_BuildKeys; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildKeysActions set) { return set.Get(); }
        public void AddCallbacks(IBuildKeysActions instance)
        {
            if (instance == null || m_Wrapper.m_BuildKeysActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuildKeysActionsCallbackInterfaces.Add(instance);
            @MultiBuild.started += instance.OnMultiBuild;
            @MultiBuild.performed += instance.OnMultiBuild;
            @MultiBuild.canceled += instance.OnMultiBuild;
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @Upgrade.started += instance.OnUpgrade;
            @Upgrade.performed += instance.OnUpgrade;
            @Upgrade.canceled += instance.OnUpgrade;
        }

        private void UnregisterCallbacks(IBuildKeysActions instance)
        {
            @MultiBuild.started -= instance.OnMultiBuild;
            @MultiBuild.performed -= instance.OnMultiBuild;
            @MultiBuild.canceled -= instance.OnMultiBuild;
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @Upgrade.started -= instance.OnUpgrade;
            @Upgrade.performed -= instance.OnUpgrade;
            @Upgrade.canceled -= instance.OnUpgrade;
        }

        public void RemoveCallbacks(IBuildKeysActions instance)
        {
            if (m_Wrapper.m_BuildKeysActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuildKeysActions instance)
        {
            foreach (var item in m_Wrapper.m_BuildKeysActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuildKeysActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuildKeysActions @BuildKeys => new BuildKeysActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IMouseActions
    {
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnMiddle(InputAction.CallbackContext context);
    }
    public interface ICameraInGameActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
    public interface IBuildKeysActions
    {
        void OnMultiBuild(InputAction.CallbackContext context);
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnUpgrade(InputAction.CallbackContext context);
    }
}
